<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.04" />
    <xacro:property name="lidar_length" value="0.03" />

    <joint name="chassis_lidar_joint" type="fixed" >
        <parent link="chassis_link" />
        <child link="lidar_frame" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    
    <link name="lidar_frame">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="${chassis_length / 3.0} 0 ${chassis_height}" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${2*lidar_radius}" h="${2*lidar_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

  <gazebo reference="lidar_frame">
        <material>Gazebo/Black</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>