<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTIES -->

    <xacro:property name="chassis_length" value="0.35" />
    <xacro:property name="chassis_width" value="0.2" />
    <xacro:property name="chassis_height" value="0.03" />
    <xacro:property name="frame_length" value="0.06" />
    <xacro:property name="frame_width" value="0.02" />
    <xacro:property name="frame_height" value="0.02" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.06" />

    <!-- BASE FOOTPRINT LINK -->

    <link name="base_footprint" />

    <!-- CHASSIS LINK -->
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="chassis_link" />
        <origin xyz="0 0 ${wheel_radius + frame_length}" rpy="0 0 0"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="3.0" l="${2*chassis_length}" w="${2*chassis_width}" h="${2*chassis_height}"
                           xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0" />
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- FRAME MACRO -->

     <xacro:macro name="frame_link" params="prefix">
        <link name="${prefix}_frame_link">
            <visual>
                <geometry>
                    <box size="${frame_length} ${frame_width} ${frame_height}" />
                </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi / 2.0} 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${frame_length} ${frame_width} ${frame_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi / 2.0} 0" />
        </collision>
        <xacro:box_inertia m="0.7" l="${2*frame_length}" w="${2*frame_width}" h="${2*frame_height}"
                           xyz="0 0 0" rpy="0 ${pi / 2.0} 0" />
        </link>
    </xacro:macro>

    <!-- WHEEL MACRO -->

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="blue" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.7" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <!-- BACK RIGHT FRAME LINK -->

    <joint name="chassis_back_right_frame_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="back_right_frame_link" />
        <origin xyz="${-(chassis_length - frame_width) / 2.0} ${-(chassis_width - frame_width) / 2.0  }  ${-frame_length / 2.0} "
                rpy="0 0 0" />
    </joint>

    <xacro:frame_link prefix="back_right" />

    <gazebo reference="back_right_frame_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- BACK LEFT FRAME LINK -->

    <joint name="chassis_back_left_frame_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="back_left_frame_link" />
        <origin xyz="${-(chassis_length - frame_width) / 2.0} ${(chassis_width - frame_width) / 2.0  }  ${-frame_length / 2.0} "
                rpy="0 0 0" />
    </joint>

    <xacro:frame_link prefix="back_left" />

    <gazebo reference="back_left_frame_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- FRONT RIGHT FRAME LINK -->

    <joint name="chassis_front_right_frame_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="front_right_frame_link" />
         <origin xyz="${(chassis_length - frame_width) / 2.0} ${-(chassis_width - frame_width) / 2.0  }  ${-frame_length / 2.0} "
                rpy="0 0 0" />
    </joint>


    <xacro:frame_link prefix="front_right" />

    <gazebo reference="front_right_frame_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- FRONT LEFT FRAME LINK -->

    <joint name="chassis_front_left_frame_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="front_left_frame_link" />
         <origin xyz="${(chassis_length - frame_width) / 2.0} ${(chassis_width - frame_width) / 2.0  }  ${-frame_length / 2.0} "
                rpy="0 0 0" />
    </joint>

    <xacro:frame_link prefix="front_left" />

    <gazebo reference="front_left_frame_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- BACK RIGHT WHEEL LINK -->

    <joint name="back_right_frame_wheel_joint" type="continuous">
        <parent link="back_right_frame_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="0 ${-(frame_width + wheel_length) / 2.0} ${-(frame_length / 2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="back_right" />

    <gazebo reference="back_right_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- BACK LEFT WHEEL LINK -->

    <joint name="back_left_frame_wheel_joint" type="continuous">
        <parent link="back_left_frame_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="0 ${(frame_width + wheel_length) / 2.0} ${-(frame_length / 2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="back_left" />

    <gazebo reference="back_left_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- FRONT RIGHT WHEEL LINK -->

    <joint name="front_right_frame_wheel_joint" type="continuous">
        <parent link="front_right_frame_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 ${-(frame_width + wheel_length) / 2.0} ${-(frame_length / 2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_right" />

    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <!-- FRONT LEFT WHEEL LINK -->

    <joint name="front_left_frame_wheel_joint" type="continuous">
        <parent link="front_left_frame_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 ${(frame_width + wheel_length) / 2.0} ${-(frame_length / 2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_left" />

    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

</robot>